"""AI functions for PR content generation."""

from typing import Optional

from pydantic import BaseModel, Field
from pydantic_ai import Agent
from pydantic_ai.models import ModelSettings

from .config import get_model_name


# Custom exceptions
class AIError(Exception):
    """Raised when AI generation fails."""
    pass


# Pydantic models
class PRContent(BaseModel):
    """PR title and description generated by AI."""
    title: str = Field(description="Concise PR title (max 72 chars)")
    description: str = Field(description="PR description summarizing the changes")


def create_pr_agent() -> Agent:
    """Create a PydanticAI agent for PR generation."""
    model_name = get_model_name()

    if not model_name:
        raise AIError("LAZYPR_MODEL environment variable not set")

    # Create agent with structured output
    agent = Agent(
        model=model_name,
        output_type=PRContent,
        system_prompt="""You are a helpful assistant that generates clear and professional pull request titles and descriptions from git diffs.

Always output valid JSON with fields: title (max 72 chars), description
""",
        model_settings=ModelSettings(
            temperature=0.3,
        ),
    )

    return agent


async def generate_pr_content(diff: str, language: str = "en") -> PRContent:
    """Generate PR title and description from diff using AI."""
    agent = create_pr_agent()

    # Build language instruction
    language_names = {
        "en": "English",
        "pt": "Brazilian Portuguese",
        "es": "Spanish",
        "fr": "French",
        "de": "German",
        "zh": "Simplified Chinese",
        "ja": "Japanese",
        "ko": "Korean",
        "it": "Italian",
        "ru": "Russian",
    }
    lang_name = language_names.get(language, "English")

    prompt = f"""You are an assistant specialized in documenting Pull Requests clearly and professionally.

IMPORTANT: You must respond entirely in {lang_name}.

Analyze the provided code diff and generate a PR description following this structure:

## Description Structure

### 1. Summary (1-2 sentences)
Explain WHAT was done in terms of functionality/impact, not technical implementation.

### 2. Context and Motivation (1 short paragraph)
- Why was this change necessary?
- What problem does it solve or what functionality does it add?
- Link to issue/ticket if available

### 3. Main Changes (bullet points)
List the most significant changes:
- Use concise bullets (1 line each)
- Focus on CHANGES, not "added file X"
- Group related changes together
- Maximum 5-7 bullets (if more, group them)

### 4. Technical Details (if relevant)
Only if there are important technical decisions:
- Architecture choices
- Trade-offs considered
- Breaking changes

### 5. How to Test (if applicable)
- Steps to verify functionality
- Important edge cases

## Tone Guidelines
- Use clear and direct language
- Avoid unnecessary jargon
- Be concise but complete
- Write thinking of the reviewer (don't assume they know all the context)

## What NOT to do
- Don't list every modified file (the diff already shows that)
- Don't use generic phrases like "code improvements"
- Don't copy commit messages directly
- Don't be overly technical in the summary

---

Now generate the PR title and description for the following diff:

```diff
{diff}
```

Provide output as JSON with fields: title, description"""

    result = await agent.run(prompt)
    return result.output
